spring.application.name=clouds5spring
spring.datasource.url=jdbc:postgresql://localhost:5432/clouds5
spring.datasource.username=postgres
spring.datasource.password=etu003144

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

spring.datasource.sql-script-encoding=UTF-8
spring.datasource.driver-class-name=org.postgresql.Driver

# Activation de Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Personnalisation
springdoc.swagger-ui.tagsSorter=alpha
springdoc.api-docs.groups.enabled=true

